language: python

python:
- 3.6
- 3.7

dist: xenial

sudo: true

addons:
  apt_packages:
  - libcups2-dev

services:
- mysql

install:
- pip install --upgrade pip
- pip install flake8 coverage codecov tox-travis

before_script:
- flake8 mempass
- mysql -e 'create database edc character set utf8;'

script:
- coverage run -m tox

after_success:
- codecov

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
